pipeline {
    agent any 

    environment {
        DOCKERHUB_USERNAME = 'aravindreddy9548'
        DOCKERHUB_CREDS = 'dockerhub-creds' 
        KUBECONFIG_CREDS = 'kubeconfig-minikube'
    }

    stages {
        
        stage('Debug Environment') {
            steps {
                echo '--- DEBUGGING ENVIRONMENT ---'
                // 1. Check if Docker is found
                bat 'where docker'
                // 2. Check if Docker engine is running
                bat 'docker info'
                // 3. Check if kubectl is found
                bat 'where kubectl'
                // 4. Check if kubectl can talk to Minikube
                withCredentials([file(credentialsId: KUBECONFIG_CREDS, variable: 'KUBECONFIG_FILE')]) {
                    bat '''
                        @echo on
                        set KUBECONFIG=%KUBECONFIG_FILE%
                        kubectl version --client
                    '''
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('Kubernetics_P'){
                echo 'Building Frontend image...'
                // Added @echo on to see the full command
                bat '''
                    @echo on
                    docker build -t %DOCKERHUB_USERNAME%/unit-converter-frontend:latest ./frontend
                '''
                
                echo 'Building API Server image...'
                bat '''
                    @echo on
                    docker build -t %DOCKERHUB_USERNAME%/unit-converter-api:latest ./api-server
                '''

                echo 'Building Compute Worker image...'
                bat '''
                    @echo on
                    docker build -t %DOCKERHUB_USERNAME%/unit-converter-compute:latest ./compute-worker
                '''
            }
            }

        }

        stage('Push to Docker Hub') {
            steps {

                echo 'Logging in to Docker Hub...'
                withCredentials([usernamePassword(credentialsId: DOCKERHUB_CREDS, usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    bat '''
                        @echo on
                        docker login -u %USER% -p %PASS%
                    '''
                }
                
                echo 'Pushing images...'
                bat '''
                    @echo on
                    docker push %DOCKERHUB_USERNAME%/unit-converter-frontend:latest
                    docker push %DOCKERHUB_USERNAME%/unit-converter-api:latest
                    docker push %DOCKERHUB_USERNAME%/unit-converter-compute:latest
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('Kubernetics_P'){
                echo 'Deploying to Minikube cluster...'
                withCredentials([file(credentialsId: KUBECONFIG_CREDS, variable: 'KUBECONFIG_FILE')]) {
                    bat '''
                        @echo on
                        set KUBECONFIG=%KUBECONFIG_FILE%
                        echo Applying configurations...
                        kubectl apply -f k8_s/
                        
                        echo Force restarting pods...
                        kubectl delete pods --all
                    '''
                }
                }
            }
        }
    }
    
    post {
        always {
            echo 'Logging out of Docker Hub...'
            // We use try/catch in shell logic (|| exit 0) to ensure it doesn't fail the build
            bat 'docker logout || exit 0'
        }
    }
}