apiVersion: v1
kind: Service
metadata:
  name: kafka-new
spec:
  ports:
  - port: 29092
    name: internal
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.6.0
        ports:
        - containerPort: 29092
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-new:2181"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-new:29092"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
            value: "0"
          # --- DEBUGGING VARIABLES ---
          - name: KAFKA_LOG4J_ROOT_LOGLEVEL
            value: "DEBUG"
          - name: KAFKA_LOG4J_LOGGERS
            value: "kafka.controller=DEBUG,state.change.logger=DEBUG"